### ISSUE TITLE
Sources in the repo

### ISSUE THREAD

**Issue by Victor-Bo** [Yttrium-tYcLief/RUUE01HD#2]
Hey! I know this project is not maintained anymore due to a lack of time so could you upload the sources on the repo so that we can take the project and maintain it?

**Comment by Yttrium-tYcLief** [comment]
Certainly. The only issue is that I can't upload my dump folder for copyright reasons.

**Comment by Yttrium-tYcLief** [comment]
I just pushed everything I have. The "common" folder is for common templates, like trees, grass, etc. The "done" folder is for completed vector files in their source (PSD) format. The "load" folder is for the PNG outputs of those source files, for direct loading into the game. The WIP folder is just what I was currently working on at the time.

On my own system I also have "dump" and "todo" folders - the "dump" is taken directly from Dolphin's texture dump as I play the game, and "todo" is where I move "dump" textures to when I plan to vectorize them.
